### ISSUE TITLE
sbb Can board

### ISSUE THREAD

**Issue by ITTV-tools** [nhchiu/VoronMods#10]
could you please create a version for of the Large Gear Clockwork for the ebb2240 ?
https://github.com/bigtreetech/EBB/blob/master/EBB%20SB2240_2209%20CAN/Custom%20Printed%20Parts/main_body_EBB_SB.stl

**Comment by appleimperio** [comment]
This would be great!

**Comment by Zephyrus67** [comment]
I doubt that will be possible. The EBB 2240/2209 boards are too high and will conflict with one of the gears in the extruder. And moving the 2 gripping gears will most likely not be possible due to the path for the filament.

But lets see what the author comes up with.

The alternative could be to use EBB36 CAN (for nema 14) or EBB42 CAN (for nema 17) along with a hartk 2 piece PCB board.

**Comment by nhchiu** [comment]
Sorry, somehow I missed this topic.

As @Zephyrus67 said, the EBB 2240/2209 board is too large and will interfere the lower gear.
Unfortunately I haven't found out an arrangement to make it fit without making major modifications like making the SB front cover wider or things like that. I'd like to keep the footprint as close to the stock CW2 as possible.
